- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: yes
    
- name: Start mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes  

- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql
    state: present    

- name: Create a new database 
  community.mysql.mysql_db:
    name: kaizen
    state: present     