- name: Install apache
  ansible.builtin.apt:
    name: "{{ package }}"
    state: present
    update_cache: yes
    
- name: Start apache
  ansible.builtin.service:
    name: "{{ package }}"
    state: "{{ service }}"
    enabled: yes   