- hosts: all
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.apt:
      name: unzip
      state: absent
    notify: Start apache  

  handlers:
  - name: Start apache
    ansible.builtin.service:
      name: apache2
      state: restarted
      enabled: yes      